
cogs:
- name: bagels/Bagels
- name: productivity/Productivity
- name: farkle/Farkle
- name: announcements/Announcements
- name: othello/Othello
- name: define/Define
- name: distributed/Node
  args:
    callerid: bagelbot
- name: astronomy/Astronomy
- name: haiku/Haiku
- name: unprompted/Unprompted
- name: voice/Voice
- name: remindme/Reminders
  args:
    deploy_hostname: slingshot
- name: camera/Camera
  args:
    cameras:
    - name: picam
      type: picamera
      desc: ""
      sunrise: false
    - name: owen_cam
      type: bagelnet
      desc: owenbot/owen_cam
      sunrise: false
- name: ticker/Ticker
- name: debug/Debug
- name: miscellaneous/Miscellaneous
- name: minecraft/Minecraft
  args:
    server_node_name: owenbot
- name: cross_stitch/CrossStitch
- name: mangle/Mangle
  args:
    strength: 50

alerts_channel: 908165358488289311
identity: DISCORD_TOKEN
prefixes: ["bb ", "Bb ", "BB ", "bB "]
